spring:
  application:
    name: service-a
  cloud:
    kubernetes:
      discovery:
        enabled: true
        all-namespaces: true
      loadbalancer:
        mode: pod
feign:
  client:
    config:
      default:
        connectTimeout: 5000
        readTimeout: 5000
        loggerLevel: FULL
      log-client:
        loggerLevel: FULL

server:
  port: 8080

logging:
  level:
    com.autoever: DEBUG
    feign: DEBUG

